[package]
name = "apple-codesign"
version = "0.22.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
rust-version = "1.70"
license = "MPL-2.0"
description = "Pure Rust interface to code signing on Apple platforms"
keywords = ["apple", "macos", "codesign"]
homepage = "https://github.com/indygreg/apple-platform-rs"
repository = "https://github.com/indygreg/apple-platform-rs.git"
readme = "README.md"

[[bin]]
name = "rcodesign"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.75"
aws-config = { version = "0.57.1", optional = true }
aws-sdk-s3 = { version = "0.35.0", optional = true }
aws-smithy-http = {version = "0.57.1", optional = true }
aws-smithy-types = {version = "0.57.1", optional = true }
base64 = "0.21.5"
bcder = "0.7.3"
bitflags = "2.4.1"
bytes = "1.5.0"
clap = { version = "4.4.7", features = ["derive"] }
chrono = "0.4.31"
cryptographic-message-syntax = "0.25.0"
der = {  version = "0.7.8", features = ["alloc"] }
dialoguer = "0.11.0"
difference = "2.0.0"
digest = "0.10.7"
dirs = "5.0.1"
elliptic-curve = { version = "0.13.6", features = ["arithmetic", "pkcs8"] }
env_logger = "0.10.0"
filetime = "0.2.22"
glob = "0.3.1"
goblin = "0.7.1"
hex = "0.4.3"
log = "0.4.20"
md-5 = "0.10.6"
minicbor = { version = "0.20.0", features = ["derive", "std"] }
oid-registry = "0.6.1"
once_cell = "1.18.0"
p12 = "0.6.3"
p256 = { version = "0.13.2", default-features = false, features = ["arithmetic", "pkcs8", "std"] }
pem = "3.0.2"
pkcs1 = { version = "0.7.5", features = ["alloc", "std", "pkcs8"] }
pkcs8 = { version = "0.10.2", features = ["alloc", "std"] }
plist = "1.5.1"
rand = "0.8.5"
rasn = "0.11.0"
rayon = "1.8.0"
regex = "1.10.2"
reqwest = { version = "0.11.22", default-features = false, features = ["blocking", "json", "rustls-tls"] }
ring = "0.17.5"
rsa = "0.9.3"
scroll = "0.11.0"
sha2 = "0.10.8"
semver = "1.0.20"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
serde_yaml = "0.9.27"
signature = { version = "2.1.0", features = ["std"] }
simple-file-manifest = "0.11.0"
spake2 = "0.4.0"
spki = { version = "0.7.2", features = ["pem"] }
subtle = "2.5.0"
tempfile = "3.8.1"
thiserror = "1.0.50"
tokio = { version = "1.33.0", features = ["rt"] }
tungstenite = { version = "0.20.1", features = ["rustls-tls-native-roots"] }
uuid = { version = "1.5.0", features = ["v4"] }
x509 = "0.2.0"
x509-certificate = "0.22.0"
xml-rs = "0.8.19"
yasna = "0.5.2"
yubikey = { version = "0.8.0", optional = true, features = ["untested"] }
zeroize = { version = "1.6.0", features = ["zeroize_derive"] }
zip = { version = "0.6.6", default-features = false, features = ["deflate"] }
zip_structs = "0.2.1"

[dependencies.app-store-connect]
path = "../app-store-connect"
version = "0.1.0-pre"
optional = true

[dependencies.apple-bundles]
path = "../apple-bundles"
version = "0.17.0-pre"

[dependencies.apple-flat-package]
path = "../apple-flat-package"
version = "0.13.0-pre"

[dependencies.apple-xar]
path = "../apple-xar"
version = "0.13.0-pre"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = { version = "2.9.2", features = ["OSX_10_12"] }
security-framework-sys = { version = "2.9.1", features = ["OSX_10_12"] }

[dev-dependencies]
indoc = "2.0.4"

[dev-dependencies.trycmd]
git = "https://github.com/indygreg/trycmd"
rev = "32e9de6feb47b35d5b8e338feb555a9981778f24"
version = "0.14.16"

[features]
default = ["notarize"]
notarize = [
    "app-store-connect",
    "aws-config",
    "aws-sdk-s3",
    "aws-smithy-http",
    "aws-smithy-types",
]
smartcard = ["yubikey"]
