[package]
name = "app-store-connect"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
license = "Apache-2.0 OR MIT"
description = "Apple App Store Connect API and client"
keywords = ["apple"]
homepage = "https://github.com/indygreg/apple-platform-rs"
repository = "https://github.com/indygreg/apple-platform-rs.git"
readme = "README.md"

[dependencies]
anyhow = "1.0.75"
base64 = "0.21.5"
clap = { version = "4.4.7", features = ["derive"] }
dirs = "5.0.1"
env_logger = "0.10.0"
jsonwebtoken = "9.1.0"
log = "0.4.20"
pem = "3.0.2"
rand = "0.8.5"
reqwest = { version = "0.11.22", default-features = false, features = ["blocking", "json", "rustls-tls-native-roots"] }
rsa = "0.9.3"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
thiserror = "1.0.50"
x509-certificate = "0.22.1"
