[package]
name = "apple-flat-package"
version = "0.11.1-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Apple flat package (.pkg) format handling"
keywords = ["apple", "flat-package", "pkgbuild", "pkg", "productbuild"]
homepage = "https://github.com/indygreg/apple-platform-rs"
repository = "https://github.com/indygreg/apple-platform-rs.git"
readme = "README.md"

[dependencies]
cpio-archive = "0.5"
flate2 = "1.0"
scroll = { version ="0.11", features = ["derive"] }
serde-xml-rs = "0.6"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[dependencies.apple-xar]
path = "../apple-xar"
version = "0.11.1-pre"
