on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
  schedule:
    - cron: '12 15 * * *'
  workflow_dispatch:
jobs:
  build-and-test:
    uses: indygreg/actions/.github/workflows/rust-workspace-build-and-test.yml@fdc5fa4bf2047873edcffb833abdb0d1615a6ccb
    with:
      actions_ref: "fdc5fa4bf2047873edcffb833abdb0d1615a6ccb"
      msrv: "1.64.0"
      sccache_s3_bucket: apple-platform-rs-sccache
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
