on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
  schedule:
    - cron: '12 15 * * *'
  workflow_dispatch:
jobs:
  build-and-test:
    uses: indygreg/actions/.github/workflows/rust-workspace-build-and-test.yml@05d9375dd6ae793586e9ffb4be3f8808da28bbac
    with:
      actions_ref: "05d9375dd6ae793586e9ffb4be3f8808da28bbac"
      msrv: "1.70.0"
      sccache_s3_bucket: apple-platform-rs-sccache
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
